FROM node:10

WORKDIR /usr/src/server

RUN echo "Dockerfile.dev of node-starter building"

# Dependencies
COPY package.json ./
COPY yarn.lock ./

# App logic & compilation
COPY .env ./
COPY .babelrc ./
COPY src/ ./src/ 

RUN yarn install

# Shares 60124 port with .prod
EXPOSE 9909
CMD ["yarn", "run", "dev:vanillaModule"]
