FROM node:10

WORKDIR /usr/src/server
RUN echo "Dockerfile.prod of node-starter building"

COPY package.json ./
COPY yarn.lock ./
COPY .env ./
COPY build/ ./build/

RUN yarn install --prod

EXPOSE 9909
CMD ["yarn", "run", "production:server"]
